version: 23.12
server:
  ssl:
    key: ks:server_keys/server_key
    certificate: ks:server_keys/server_cert
    trust_certificates:
      - "@iviadc-ca.pem"
definition:
  id: 1
  name: OIDC Definition
  grant_types:
    - authorization_code
    - implicit
    - password
    - client_credentials
    - refresh_token
    - urn:ietf:params:oauth:grant-type:pre-authorized_code
  authorization_details_types_supported:
    - type: openid_credential
      strategy: sha512
      script: null    
  ignore_unknown_authorization_details_type: false
  base_url: https://iviadcgw:8443
  token_settings:
    issuer: https://iviadcgw:8443/oauth2
    signing_alg: RS256
    signing_keystore: isvaop_signing
    signing_keylabel: rsakey
    access_token_type: jwt
  features:
    consent_prompt: NEVER_PROMPT
  ropc_mappingrule_id: ropc
  pre_mappingrule_id: pretoken
  pre_auth_settings:
    pre_authorize_code_lifetime: 1800
    require_transaction_code: true
    transaction_code_charset: 123456789
    transaction_code_length: 4
logging:
  level: debug

authentication:
  endpoint: "/locallogin"
  callback_param_name: ""
  subject_attribute_name: ""
  credentials_jwt:
    signature_validation_enforcement: false
  ssl:
    certificate:
      - "@iviadc-ca.pem"
    disable_hostname_verification: false

jwks:
  signing_keystore: isvaop_signing
keystore:
  - name: server_keys
    type: pem
    certificate:
      - label: server_cert
        content: "@iviadcop_pub.crt"

    key:
      - label: server_key
        content: "@iviadcop_priv.key"

  - name: isvaop_signing
    type: pem
    key:
      - label: rsakey
        content: "@iviadcop_priv.key"

  - name: postgres
    type: pem
    certificate:
      - label: pg_pub_cert
        content: "@iviadcdb_pub.crt"

runtime_db: hvdb
session_cache:
  type: in-memory

server_connections:
  - name: hvdb
    type: postgresql
    database_name: iviadc
    hosts:
      - hostname: iviadcdb
        hostport: 5432
    credential:
      username: iviadc
      password: passw0rd
    ssl:
      certificate:
        - ks:postgres/pg_pub_cert

rules:
  mapping:
    - name: pretoken
      rule_type: javascript
      content: "@pretoken.js"
    - name: preauth_userauth
      rule_type: javascript
      content: "@preauth_userauth.js"
    - name: preauth_notifytxcode
      rule_type: javascript
      content: "@preauth_notifytxcode.js"

dynamic_registration:
  registration_endpoint_authentication:
    require_bearer_token: true
    allow_custom_client_creds: true
  management_endpoint_authentication:
    require_bearer_token: true
  registration_access_token:
    generate: false
    lifetime: 86400
    scopes:
      - cdr:registration

clients:
  - client_id: 00000000-0000-4000-8000-000000000000
    client_name: Administrator for tenant0
    client_secret: secret
    enabled: true
    grant_types:
      - client_credentials
    scopes:
      - "admin"
    extension:
      tenantUUID: "00000000-0000-4000-8000-000000000000"
  - client_id: 00000000-0000-4000-8000-000000000000_vcholders
    client_name: VC Holder
    enabled: true
    grant_types:
      - password
      - refresh_token
    extension:
      tenantUUID: "00000000-0000-4000-8000-000000000000"
      isHolder: "true"
  - client_id: 11111111-1111-4111-8111-111111111111
    client_name: Administrator for tenant1
    client_secret: secret
    enabled: true
    grant_types:
      - client_credentials
    scopes:
      - "admin"
    extension:
      tenantUUID: "11111111-1111-4111-8111-111111111111"
  - client_id: 11111111-1111-4111-8111-111111111111_vcholders
    client_name: VC Holder for tenant1
    enabled: true
    grant_types:
      - password
      - refresh_token
    extension:
      tenantUUID: "11111111-1111-4111-8111-111111111111"
      isHolder: "true"
  - client_id: onpremise_vcholders
    client_name: VC Holder
    enabled: true
    grant_types:
      - password
      - refresh_token
  - client_id: localdeploy_dmv_client
    client_name: Relying Party Client for the DMV app
    client_secret: localdeploy_dmv_client_secret
    enabled: true
    grant_types:
      - authorization_code
    response_types:
      - code
    redirect_uris:
      - http://localhost:8090/logincallback
  - client_id: admin
    client_name: Administrator for the deployment
    client_secret: secret
    enabled: true
    grant_types:
      - client_credentials
    scopes:
      - cdr:registration
  - client_id: default_oid4vci_wallet
    client_name: OID4VCI Untrusted Wallets
    enabled: true
    grant_types:
      - authorization_code
      - urn:ietf:params:oauth:grant-type:pre-authorized_code
    response_types:
      - code
    authorization_details_types:
      - openid_credential
    act_as_credential_issuer: true
    redirect_uris:
      - openid-credential-offer://
      - openid-credential-wallet://
      - openid-credential-offer://callback
      - eudi-openid4ci://authorize

